from . import res_partner
from . import samra_metrics
from . import samra_analytics
from . import samra_consent
from . import samra_transfer
from . import samra_demo_data
from . import product_template
from . import sale_order
from . import samra_wishlist
from . import samra_viewed_product
from . import samra_whatsapp_log
from . import samra_dashboard
from . import samra_occasions
from . import samra_recommendations
from . import samra_flow
